### ISSUE TITLE
How to use in angular

### ISSUE THREAD

**Issue by patidarhemendra1** [nolanlawson/emoji-picker-element#111]
Hello Team,
I am trying to use it in angular application when I add <emoji-picker></emoji-picker> in html its asking  add as a angular component.
But I don't see any module exposed in library

**Comment by nolanlawson** [comment]
Hi, I haven't used Angular recently (I assume you're talking about recent versions of Angular and not AngularJS v1?), but in general [web components should work out-of-the-box in Angular](https://custom-elements-everywhere.com/libraries/angular/results/results.html). You might want to use StackOverflow to look for how to import custom elements into Angular, for instance [this thread](https://stackoverflow.com/questions/58372328/custom-web-component-and-angular) or [this blog post](https://alligator.io/angular/using-custom-elements/).

Hope that helps! Closing this issue for now as it's more a question than a bug report or feature request.
