### ISSUE TITLE
Minor optimization note

### ISSUE THREAD

**Issue by mustafa0x** [nolanlawson/emoji-picker-element#12]
https://github.com/nolanlawson/emoji-picker-element/blob/master/src/picker/utils/requestAnimationFrame.js#L1

While this may make the bundle size smaller, it'll make the compressed size larger.

**Comment by nolanlawson** [comment]
True yes, it was kind of a silly thing to target. Perhaps I should remove it.

**Comment by nolanlawson** [comment]
I tested it out, and actually the brotli size is not affected (at least, within a rounding error).

```
# with rAF fix
 PASS  ./bundle.js: 39.82KB < maxSize 40KB (no compression)
 PASS  ./bundle.js: 12.35KB < maxSize 15KB (brotli)
# without rAF fix
 PASS  ./bundle.js: 39.87KB < maxSize 40KB (no compression)
 PASS  ./bundle.js: 12.35KB < maxSize 15KB (brotli)
```
