### ISSUE TITLE
Error if it is not used in body element

### ISSUE THREAD

**Issue by thebestgin** [nolanlawson/emoji-picker-element#122]
Error if it is not used in body element.

`import 'emoji-picker-element';`
`<emoji-picker></emoji-picker>`

picker.js:2403 Uncaught TypeError: Cannot set property 'scrollTop' of null
    at eval (picker.js:2403)

`rAF(() => {
   // reset scroll top to 0 when emojis change
   $$invalidate(6, tabpanelElement.scrollTop = 0, tabpanelElement);
});`

**Comment by nolanlawson** [comment]
In what situations would `emoji-picker-element` not be in the `<body>`? I take it you're inserting it into the `<head>`? But isn't it unusable in that case?

**Comment by nolanlawson** [comment]
I can't repro ([here is my attempt](https://bl.ocks.org/nolanlawson/raw/81c63c92aa00c91b037621d3d18f337c/)), either by putting the emoji picker in the `<head>` or after the `<body>`. Which browser are you using? Do you have a reproducible test?

**Comment by nolanlawson** [comment]
Please reopen if this is still an issue. I wasn't able to reproduce using the steps provided.
