### ISSUE TITLE
Issue on Edge: Expected identifier, string or number

### ISSUE THREAD

**Issue by niktsanov** [nolanlawson/emoji-picker-element#123]
Hey there!
Thanks for the awesome package, we really enjoy using it and we have implemented it as a tooltip in our vue project. However, we’ve noticed issues in our reporting tool piling up on Edge (EdgeHTML: 18.17763):
```
Expected identifier, string or number in picker.js  2011  13  currentSkinTone(...)
```
Backtrace:
```
fireEvent(“emoji-click”, {
--
2010 | emoji,
2011 | skinTone: currentSkinTone, <---
2012 | ...skinTonedUnicode && { unicode: skinTonedUnicode },
2013 | ...emojiSummary.name && { name: emojiSummary.name }
```
Any ideas how this can be resolved? Perhaps, it is a really old version of the browser, if so, is there a way to detect and maybe hide the picker? Some more context about our use case:
- We use the element inside a vue component alongside popperjs and we listen for the emoji-click which then emits another event that we use outside of the component.

Thanks for your time!

**Comment by niktsanov** [comment]
I'm closing this since we ended up checking if emojis are supported alongside shadow dom and we conditionally render the vue component based on that. The issue probably originated from the fact that some browser (pre-2018) don't support these.

```
    computed: {
       emojiPickerTooltip() {
          if (this.isEmojiSupported && this.isShadowDomSupported) {
              return () => import('@/components/EmojiPickerTooltip.vue')
          }
          return null
       }
    }
```

and in the <template>:

```
<component
   :is="emojiPickerTooltip"
   @emoji-click="onEmojiClick" />
```

**Comment by nolanlawson** [comment]
Thanks and sorry for that, but this component doesn't support legacy EdgeHTML.

**Comment by wobsoriano** [comment]
For vue users, just add the `emoji-picker` element to `ignoredElements`

```js
import Vue from 'vue';

Vue.config.ignoredElements = ['emoji-picker'];
```

For nuxt users, require only in browser:

```js
if (process.browser) {
  require('emoji-picker-element');
}
```

**Comment by wobsoriano** [comment]
This is how I do it in Composition API:

```html
<template>
  <emoji-picker ref="picker"></emoji-picker>
</template>

<script>
import { defineComponent, ref, onMounted, onUnmounted } from 'vue';
import 'emoji-picker-element';

export default defineComponent({
  emits: ['handleSelect'],
  setup(_props, { emit }) {
    const picker = ref();

    const handleEmojiClick = (event) => {
      emit('handleSelect', event.detail);
    };

    onMounted(() => {
      picker.value?.addEventListener('emoji-click', handleEmojiClick, true);
    });

    onUnmounted(() => {
      picker.value?.removeEventListener('emoji-click', handleEmojiClick, true);
    });

    return {
      picker,
    };
  },
});
</script>
```

For nuxt:

```js
if (process.browser) {
  require('emoji-picker-element)';
}
```

Worth checking for custom elements: https://v3.vuejs.org/guide/migration/custom-elements-interop.html#overview
