### ISSUE TITLE
Allow changing category emoji size independent of other emoji size

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/emoji-picker-element#133]
Given https://github.com/nolanlawson/emoji-picker-element/issues/10#issuecomment-849394245, this seems like a sensible feature.

**Comment by ericaig** [comment]
Hello Nolan, it's great you've made plans to add this feature to this package.

While I was trying to adapt the --emoji-size to best fit my design I found this out:
![Simulator Screen Shot - iPhone 8 Plus - 2021-05-31 at 08 41 18](https://user-images.githubusercontent.com/16205258/120152880-53f6ea00-c1ee-11eb-97cb-23c7b64ca8b2.png)


Whenever you increase the size of the emoji (categories) the `transform` style on the `indicator` element miscalculates the currently selected category. In the above screenshot I have the ⛔️   selected.

Thank you for dedicating your time to give us this simple and complete `emoji-picker`

**Comment by nolanlawson** [comment]
@ericaig It appears that this only happens if the category emoji overflow horizontally (notice that the flag emoji is cut off).

Ideally with some way to control the emoji category size separately from the other ones, you should be able to have it not overflow. :slightly_smiling_face:

**Comment by ericaig** [comment]
@nolanlawson Exactly. Leaving the categories size to it's default size solves both topics (categories dedicated size variable and horizontal scroll) 👌🏾

**Comment by ericaig** [comment]
If you need help with this. I'll be glad to chip in. It would be my first time contributing to a public package (code-wise) but I know how it works 😊

**Comment by nolanlawson** [comment]
Ah sorry, I got around to it. :) ^

**Comment by nolanlawson** [comment]
Release in 1.5.0

**Comment by ericaig** [comment]
Perfect... I'll update it on my project now.. Thank you very much :)
