### ISSUE TITLE
Firefox/Safari on Mac: can't change skin tone

### ISSUE THREAD

**Issue by danburzo** [nolanlawson/emoji-picker-element#14]
The skin tone selector does not work on my Firefox 77 / macOS. For some reason, there's no `activeElement` on the `focusout` event when I click on a skin tone button.

https://github.com/nolanlawson/emoji-picker-element/blob/04f490a6cbfab567473cbcaa033d438d88b61535/src/picker/components/Picker/Picker.js#L587-L598

**Comment by nolanlawson** [comment]
That blur event should only occur when you click _outside_of the skin tone picker. If you're trying to debug this, you may just comment out that entire thing, since it will probably be a bit annoying if, whenever you click inside of the DevTools, the skin tone picker disappears.

I can't repro in Firefox 77 on Ubuntu, so I wonder if this is an OS-specific thing? I'll try to find a Mac to check.

**Comment by danburzo** [comment]
Huh, now that you mentioned... I checked and it only reproduces with an external Magic Trackpad. The Macbook's internal trackpad works fine. 🤦‍♂️

**Comment by nolanlawson** [comment]
Huh, well that's still a bug I'd like to fix... I wonder how that is possible?

**Comment by danburzo** [comment]
I'll see if I can isolate it, I'm curious as well.

**Comment by danburzo** [comment]
Okay, it seems it's purely a timing issue and that I've Skinner-boxed myself into a pattern that is not there. I haven't exactly figured out everything yet, but: the problem reproduces in Firefox _and Safari_ (but not Chrome) when you take longer between `mousedown` and `mouseup`. It just so happens that using the external trackpad I click it down (slower) while the internal trackpad I tap (faster). If you're quick enough to click the button while the next frame kicks it (as per the `await rAF` part) it works. Otherwise the list gets hidden from underneath your nose. 

Here's me holding down the trackpad on Firefox (notice the list disappears):

![ff](https://user-images.githubusercontent.com/205375/86161184-8e0ac800-bb15-11ea-91a0-67b167187e30.gif)

And here's Chrome, which on the `mousedown` already makes the button the `activeElement`, so I'm able to hold it down indefinitely:

![chrome](https://user-images.githubusercontent.com/205375/86161231-a1b62e80-bb15-11ea-9598-5e36b2f0d3dc.gif)

Let me know if you're able to reproduce this on Linux!

**Comment by nolanlawson** [comment]
Thanks for the detailed explanation. On Linux, I cannot reproduce either with a separate mouse or with my built-in Dell XPS trackpad, in either Chrome, Firefox, or GNOME Web (WebKit). I will try to grab a Mac so I can test there! (My wife has one; I'll just bug her to borrow it when she's done. :joy:)

If it's just a timing issue, then probably we can replace the `requestAnimationFrame` with something else (e.g. a `setTimeout`).

It's a shame that I can't use a more simple `relatedTarget`, but it's not supported in Safari. :disappointed:

**Comment by nolanlawson** [comment]
Confirmed reproduce in Safari on MacOS. I'll write a fix.

**Comment by danburzo** [comment]
Ah cool, let me know if I can help test it!
