### ISSUE TITLE
Support React wrapper

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/emoji-picker-element#183]
Given that React is apparently [not launching custom element support in React 18](https://dev.to/bennypowers/what-s-not-new-in-react-18-45c7), maybe we should have our own React wrapper, or at least document in the README how to do this.

**Comment by wobsoriano** [comment]
Hi, can't find a good and lightweight vue emoji picker so I published this https://github.com/wobsoriano/vuemoji-picker.

It uses emoji-picker-element and vue-demi to support Vue 2 and 3.

Thank you for this web component!

**Comment by wobsoriano** [comment]
BTW, if anyone wants a vue wrapper https://github.com/wobsoriano/vuemoji-picker
