### ISSUE TITLE
Cant load data source using CDN

### ISSUE THREAD

**Issue by popperz0r** [nolanlawson/emoji-picker-element#189]
My element has this attributes

`<emoji-picker class="light hide" data-source="/js/plugins/emoji-picker-element/pt_PT.json"></emoji-picker>
`

Im using the default setup to debug

`{
  "categories": {
    "custom": "Custom",
    "smileys-emotion": "Smileys and emoticons",
    "people-body": "People and body",
    "animals-nature": "Animals and nature",
    "food-drink": "Food and drink",
    "travel-places": "Travel and places",
    "activities": "Activities",
    "objects": "Objects",
    "symbols": "Symbols",
    "flags": "Flags"
  },
  "categoriesLabel": "Categories",
  "emojiUnsupportedMessage": "Your browser does not support color emoji.",
  "favoritesLabel": "Favorites",
  "loadingMessage": "Loading…",
  "networkErrorMessage": "Could not load emoji. Try refreshing.",
  "regionLabel": "Emoji picker",
  "searchDescription": "When search results are available, press up or down to select and enter to choose.",
  "searchLabel": "Search",
  "searchResultsLabel": "Search results",
  "skinToneDescription": "When expanded, press up or down to select and enter to choose.",
  "skinToneLabel": "Choose a skin tone (currently {skinTone})",
  "skinTones": [
    "Default",
    "Light",
    "Medium-Light",
    "Medium",
    "Medium-Dark",
    "Dark"
  ],
  "skinTonesLabel": "Skin tones"
}
`

And the console logs this error

`database.js:719 Uncaught (in promise) Error: Emoji data is in the wrong format
    at assertEmojiData (database.js:719)
    at getETagAndData (database.js:743)
    at async checkForUpdates (database.js:816)
assertEmojiData @ database.js:719
getETagAndData @ database.js:743
async function (async)
checkForUpdates @ database.js:805
_init @ database.js:857
async function (async)
_init @ database.js:848
Database @ database.js:844
_dbCreate @ picker.js:2563
(anonymous) @ picker.js:2571
Promise.then (async)
_dbFlush @ picker.js:2570
PickerElement @ picker.js:2514
(anonymous) @ picker.js:2608
`

Has this happened with anyone before?

**Comment by nolanlawson** [comment]
It looks like you're loading the `i18n` file as the data source. These are two separate things. You probably want something [like this](https://codepen.io/nolanlawson/pen/yLbMWyg).

Unfortunately it looks like setting the `i18n` on the picker doesn't work... Looks like a bug snuck through somehow. I'll take a look.

**Comment by nolanlawson** [comment]
Nevermind, I had a bug in my repro... [here is a working version](https://codepen.io/nolanlawson/pen/yLbMWyg).

Hope that helps!

**Comment by popperz0r** [comment]
Worked like a charme @nolanlawson thank you

I followed this example: https://github.com/nolanlawson/emoji-picker-element#i18n-structure
