### ISSUE TITLE
Option to custom favorites emojis

### ISSUE THREAD

**Issue by yravid** [nolanlawson/emoji-picker-element#205]
Hi,
There is a behavior which I find odd when using the picker especially when clicking an emoji from the favorites list,
Clicking on an emoji (which is not the first one) may change the favorites list order and when clicking more than once it may be replaced by another emoji and cause confusion,
Illustration: 
![Screen Recording 2021-08-09 at 10 23 21](https://user-images.githubusercontent.com/51640960/128672025-deb7f45f-af95-4604-9b96-10abe7064378.gif)
I think it would be useful to have an option to 'freeze' the favorites list and only change it before/after mounting.

Love your library! 🥇  
Thanks,
Yahav

**Comment by nolanlawson** [comment]
Hmmmm, this is a good point. I had observed this behavior but it hadn't occurred to me that it might be a problem.

I think there's a case to be made that "freezing" should just be the default behavior. I can't see a case where you'd want the favorites list to update while the picker is mounted. So maybe the favorites should be frozen throughout the entire picker lifecycle, and only updated in the `connectedCallback` phase.

**Comment by nolanlawson** [comment]
BTW can you describe your use case a bit? I had assumed that most usages are:

1. Load the picker
2. The user clicks an emoji
3. Close the picker

... in which case nobody would notice the favorites moving around. I'm curious to know if your use case is different.
