### ISSUE TITLE
Vue3 Failed to resolve component: emoji-picker

### ISSUE THREAD

**Issue by diadal** [nolanlawson/emoji-picker-element#207]
is there any you can opt for ID rather than just 
`<emoji-picker></emoji-picker>` something like `<div id="emoji-picker"></div>`
with this it can support all javascript and typescript

**Comment by nolanlawson** [comment]
Do you have a repro for the problem you're experiencing? The emoji picker should work fine in any framework, including Vue3.

And yes you can add an id to it if you like:

```html
<emoji-picker id="foo"></emoji-picker>
```

A quick search suggests you may be running into [this issue](https://www.reddit.com/r/vuejs/comments/hd5gf5/has_anyone_tried_vue_3_with_web_components/), I'm not a Vue expert so I'm not sure what to do. Supposedly [Vue fully supports custom elements](https://custom-elements-everywhere.com/libraries/vue/results/results.html).

**Comment by nolanlawson** [comment]
Closing as I believe this is a Vue-specific issue and should be resolvable. [Here is an example of using Vue 3 with `emoji-picker-element`](https://codepen.io/nolanlawson/pen/oNWOzma) if it helps. Please reopen if I'm incorrect.

**Comment by wobsoriano** [comment]
https://v3.vuejs.org/guide/web-components.html#using-custom-elements-in-vue
