### ISSUE TITLE
Need React JSX support

### ISSUE THREAD

**Issue by ponikar** [nolanlawson/emoji-picker-element#219]
This library is awesome but without JSX it's tedious to add styling in React App. 

It would be really nice if we can get JSX support, So we don't need to write like this

React.createElement("emoji-picker", {});

Something like this
<EmojiPicker />

Thank you!

**Comment by steelbrain** [comment]
@ponikar Here's my (Typescript) React wrapper around this

```typescriptreact
import 'emoji-picker-element'
import type { EmojiClickEvent } from 'emoji-picker-element/shared'
import React from 'react'

interface Props {
    onSelect: (emoji: string) => void
}

export default function EmojiPicker({ onSelect }: Props): React.ReactElement {
    const callbackRef = React.useRef<Props['onSelect']>(onSelect)

    // Since we only add the callback once to the underlying HTML element
    // and we get refs randomly. It's not a good idea to attach a different
    // listener to it on each re-render. So we attach the parent listener
    // to a local ref and call that ref value instead.
    callbackRef.current = onSelect

    const handleElementRef = React.useCallback((element: HTMLElement) => {
        if (element != null) {
            if (element.dataset['emoji-picker-registered'] == null) {
                element.setAttribute('emoji-picker-registered', 'true')
                element.addEventListener('emoji-click', event => {
                    callbackRef.current?.((event as EmojiClickEvent).detail.unicode ?? '')
                })
            }
        }
    }, [])

    // @ts-expect-error: Custom HTML Element
    return <emoji-picker ref={handleElementRef} />
}
```

Works quite well honestly

**Comment by ponikar** [comment]
// @ts-expect-error: Custom HTML Element
    return <emoji-picker ref={handleElementRef} /> 
    
  I was having the same error. Thanks

**Comment by ponikar** [comment]
Currently, If I want to use this library I have to explicitly make a React Element using this syntax. 
JSX is first-class way to use JavaScript XML in React.

instead of this
React.createElement("emoji-picker", {});

We can use this
<EmojiPicker style={..style} className={..} />

I know this library is not specific for a react only. But the current approach to using this library in react is quite tedious.

**Comment by steelbrain** [comment]
@ponikar I think you are misunderstanding

```
React.createElement("emoji-picker", {});
```
and
```
<emoji-picker />
```

are one and the same in React. JSX is transpiled down to those function calls before execution

**Comment by ponikar** [comment]
I get it at the end the both are going to work the same. 

But JSX lets you write readable and mailable Codes. (React Element). 

### JSX 
`<EmojiPicker style={{..}} className="">
     {children}
</EmojiPicker>`

### React.createElement
`React.createElement("emoji-element", {
    style: {..},
    className: "",
    children: {}
});`
 
Now you can see which is the best way to write code.

**Comment by anilanar** [comment]
@ponikar I think you have a misunderstanding on how React/JSX works. You can use `emoji-picker` with the JSX syntax. The following is valid code and it will work:

```
<emoji-picker className="light" />
```

Perhaps Typescript types or some linter is confusing you by telling you that custom components must be in PascalCase?

For typescript, check how to add new intrinsic elements here: https://www.typescriptlang.org/docs/handbook/jsx.html

**Comment by nolanlawson** [comment]
Thanks for the explanation @anilanar. Since this isn't a React-specific library, it seems there is nothing for me to do here. Although if someone would like to publish a separate React wrapper or something, maybe that would make it easier for React folks to use this project. In the meantime this library can be used in React as any custom element can.
