### ISSUE TITLE
Error: Failed to execute 'transaction' on 'IDBDatabase'  while changing routes

### ISSUE THREAD

**Issue by fayeed** [nolanlawson/emoji-picker-element#220]
While changing routes I get this error `DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing`. 

I am using this inside web component which is then imported inside a Vue app, app/ component is not crashing or anything just seeing this as an error log.

**Comment by nolanlawson** [comment]
Sounds good! Thanks.

**Comment by vmartinBT** [comment]
> What browser/OS are you seeing this in? When you say "changing routes," what do you mean exactly? Are you changing routes in a multi-page app or single-page app – i.e. are these actual page navigations, or in-app pseudo-navigations?
> 
> I'm not sure it helps, but you may want to look into the [Page Lifecycle API](https://developers.google.com/web/updates/2018/07/page-lifecycle-api). In particular, in the section on the "frozen" event, note that it recommends "Close all open IndexedDB connections." In `emoji-picker-element` this can be accomplished with:
> 
> ```js
> document.querySelector('emoji-picker').database.close()
> ```

This worked for me. Thanks!

**Comment by ekimber** [comment]
This does not work for me. Looks like the component gets unmounted by react before the database close function completes. Any suggestions?

**Comment by nolanlawson** [comment]
@ekimber Can you call `database.close()` (as described above) before the component unmounts?

**Comment by ekimber** [comment]
> @ekimber Can you call `database.close()` (as described above) before the component unmounts?

I can call it before it unmounts, however, it is of course async, and from what I can observe, the unmount is occurring before the close promise completes

**Comment by ekimber** [comment]
Actually that may be wrong. I tried pausing execution there but it doesn't help.
 Here is the stack trace:
```database.js:156 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at eval (http://localhost:8280/_js/compiled/cljs-runtime/module$node_modules$emoji_picker_element$database.js:4:118)
    at new Promise (<anonymous>)
    at dbPromise (http://localhost:8280/_js/compiled/cljs-runtime/module$node_modules$emoji_picker_element$database.js:4:74)
    at get (http://localhost:8280/_js/compiled/cljs-runtime/module$node_modules$emoji_picker_element$database.js:14:68)
    at eval (http://localhost:8280/_js/compiled/cljs-runtime/module$node_modules$emoji_picker_element$database.js:9:76)
    at Array.map (<anonymous>)
    at hasData (http://localhost:8280/_js/compiled/cljs-runtime/module$node_modules$emoji_picker_element$database.js:9:67)
    at checkForUpdates (http://localhost:8280/_js/compiled/cljs-runtime/module$node_modules$emoji_picker_element$database.js:23:421)```

**Comment by nolanlawson** [comment]
You might need to do an [unhandled rejection](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event) event listener or something.

`database.close().catch(() => {})` may also work. This is a good blog post on the subject: https://jakearchibald.com/2023/unhandled-rejections/

**Comment by ekimber** [comment]
Thanks, I managed to get rid of the warning by doing this `database.close().catch(() => {})` 
I have to do it as soon as the component is mounted. Odd, but it still seems to function ok.
