### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'transaction')

### ISSUE THREAD

**Issue by tangxunhu** [nolanlawson/emoji-picker-element#225]
Hi! I use the component in Vue Element UI. include into the tag 'el-popover'. But when I first clicked,  will show error:
![image](https://user-images.githubusercontent.com/24522611/134287276-7b6c797f-2ccb-490b-8ee5-b916ce60800e.png)
![image](https://user-images.githubusercontent.com/24522611/134287493-5ba1c35d-abac-44b8-895b-8c6878edae47.png)
but if I use in common tag ,like 'div' . it has no error. So if it  has  other init skill for the component. thanks

**Comment by nolanlawson** [comment]
Hi, can you show me the line of code that is throwing the error? The `Cannot read properties of undefined (reading 'transaction')`? I'm guessing it's this line, but I'm not sure:

https://github.com/nolanlawson/emoji-picker-element/blob/d732610e7fede78df4e9bbc6ce964690d2fe4adf/src/database/databaseLifecycle.js#L55

Which browser is this happening in? Or is it an app like Electron or something? Do you have a reproducible test case, since I'm not familiar with "Vue Element UI"?

**Comment by tangxunhu** [comment]
hava a look, thanks!
https://codepen.io/tangxunhu/pen/PojxZGa

**Comment by nolanlawson** [comment]
It looks like there's an error in the console:

    [Vue warn]: Unknown custom element: <emoji-picker> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I googled it and found [this StackOverflow answer](https://stackoverflow.com/a/50408652). So I added:

```js
 components {
   'emoji-picker': Picker
  } 
```

[This appears to work](https://codepen.io/nolanlawson/pen/oNwQzQp), although your example may need some more work to get the popover working correctly.

I hope that helps! Please let me know if you think there is a bug in this library, but it appears to me to be a Vue configuration issue.

**Comment by nolanlawson** [comment]
On second thought, there appears to be a race condition. If you attach the element, remove it, and then attach it again with a very particular timing, I can occasionally reproduce the error you found. [Repro](https://codepen.io/nolanlawson/pen/GREwNoe)

I'm not sure why your Vue code was removing and re-attaching the element, but avoiding that will fix your issue in the short term. In the long term, I'd like to fix this race condition.

**Comment by nolanlawson** [comment]
Thanks for reporting the bug; fixed in v1.8.2.

**Comment by tangxunhu** [comment]
thanks a lots。
ありがとうございました
