### ISSUE TITLE
Picker no longer works in Firefox extensions after v1.5.0

### ISSUE THREAD

**Issue by jzhao67** [nolanlawson/emoji-picker-element#229]
I have been using `emoji-picker-element` v1.5.0 in a Firefox extension. Although there are errors in the console, it doesn't seem to affect the functionality of the picker. Upon updating to any version after v1.5.0, the picker element is no longer visible and has no child elements when looking at it using the devtools inspector. 

I created a sample extension to demonstrate: [emoji-picker-extension.zip](https://github.com/nolanlawson/emoji-picker-element/files/7422025/emoji-picker-extension.zip). There are instructions in the README. 

I suspect that this is related to [this bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1716685).

**Comment by jzhao67** [comment]
Thanks for the response. I tried using `dataSource` to load `https://cdn.jsdelivr.net/npm/emoji-picker-element@^1/index.js`, and it did stop the NetworkError from happening. 

Separately, I did manage to get a custom elements polyfill working for custom elements added from the extension. The latest version of emoji-picker-element now works when the content script looks like this:
```
const script = document.createElement("script");
script.text = `
	window.customElements.forcePolyfill = true;

	const emojiScript = document.createElement("script");
	emojiScript.src = "https://cdn.jsdelivr.net/npm/emoji-picker-element@^1/index.js";
	emojiScript.type = "module";
	document.head.append(emojiScript);

	const wcPolyfillScript = document.createElement("script");
	wcPolyfillScript.src = "https://unpkg.com/@webcomponents/webcomponentsjs@^2/webcomponents-bundle.js";
	document.head.append(wcPolyfillScript);
`;

document.addEventListener("WebComponentsReady", () => {
	const picker = document.createElement("emoji-picker");
	document.body.prepend(picker);
});

document.head.append(script);
```
Here's the complete extension with the latest version of emoji-picker and the polyfill: [emoji-picker-extension-polyfilled.zip](https://github.com/nolanlawson/emoji-picker-element/files/7516418/emoji-picker-extension-polyfilled.zip)

I had to add the script to the page head because loading the polyfill in the extension content-script didn't affect any custom elements added to the page, since the page and the content-script are separate JS contexts. Though not ideal, it is workable.

**Comment by nolanlawson** [comment]
Glad to hear you found a workaround! Since it seems there's nothing for this project to do, I'll close this issue for now.
