### ISSUE TITLE
It seems that the react example does not work

### ISSUE THREAD

**Issue by NansD** [nolanlawson/emoji-picker-element#231]
![screenshot](https://user-images.githubusercontent.com/18481465/141464764-f1cce2e3-957c-4cf9-9d10-dbdf5ebfb35e.png)
When going to the [example page](https://codepen.io/nolanlawson/pen/bGWmmrz), the picker looks broken.

**Comment by nolanlawson** [comment]
Which browser are you using? Are there any errors in the DevTools console? I tested in Firefox and Chrome, and both worked for me.

**Comment by nolanlawson** [comment]
Could you take a look at the new demo site? ^ I'm guessing that this will work: https://bl.ocks.org/nolanlawson/raw/fa60717eceb719b729e10d522c62c9ec/

**Comment by NansD** [comment]
sorry for not giving the name of the browser I was using, it's Brave (Chromium based).
Here is the error I get : 

```
emoji-picker-element.js:2364 DOMException: The user denied permission to access the database.
```

I guess this might be linked to the way Brave handles privacy or something like that.


The second link you sent works well !

**Comment by nolanlawson** [comment]
Yep, definitely sounds like an iframe issue. My hunch is that Brave (or some browser extension) is blocking access to IndexedDB in the iframe (in CodePen). The second demo doesn't use an iframe.
