### ISSUE TITLE
Support Twemoji (Or allow running scripts on load)

### ISSUE THREAD

**Issue by r0hin** [nolanlawson/emoji-picker-element#233]
A straightforward method is to allow running `twemoji.parse()` on the container of the emojis. Able to run it after importing the script tag [here](https://github.com/twitter/twemoji). However, I cannot do it myself due to the shadow DOM.

**Comment by nolanlawson** [comment]
This is actually something I explicitly didn't want to support – for performance and simplicity reasons, `emoji-picker-element` is designed to use the browser's built-in emoji.

I've considered supporting emoji fonts (#82) but the browser support is not great right now, and Firefox and Chrome both implement competing standards. Maybe someday this will make sense.

I'm curious to know why you want twemoji?

**Comment by r0hin** [comment]
> I'm curious to know why you want twemoji?

Basically, I really dislike the look of emojis on windows specifically- plus I've noticed emojis have irregular padding in text on some systems so sometimes it looks a bit off. On GitHub for example, I think they use default and for me, with "🏡a", the emoji bleeds into the text directly next.

**Comment by r0hin** [comment]
To add to this, some users running my webapp aren't on the latest system update and cannot see specific emojis without twemoji or some other replacement font.

**Comment by nolanlawson** [comment]
`emoji-picker-element` should automatically filter out unsupported emoji so you don't see the empty boxes. As for the padding issue you mention, I take it that that occurs with inline text and not in `emoji-picker-element` specifically?

I suppose I'm arguing that you could use native emoji for the picker, and Twemoji elsewhere in your app, but I understand if you'd prefer to have the same unified experience everywhere. When color fonts are available cross-browser, I may be interested in adding a generic way for `emoji-picker-element` to support that. (#82)

**Comment by r0hin** [comment]
> As for the padding issue you mention, I take it that that occurs with inline text and not in `emoji-picker-element` specifically?

That's correct - seems to be a general emoji issue on MacOS specifically. 

> When color fonts are available cross-browser, I may be interested in adding a generic way for `emoji-picker-element` to support that. (#82)

Sounds good. Issue is definitely low-urgency as native emoji in the picker is suitable.

**Comment by productdevbook** [comment]
I hope this support comes, because it's better that we see the same emoji designs on every device. The user should not see different design emoji between windows and macos.

**Comment by nolanlawson** [comment]
> The user should not see different design emoji between windows and macos.

I think this is debatable – arguably, iOS users are accustomed to seeing the iOS emoji, and it's weird for them to see some other design. Ditto for Android and Windows users. Sadly the state of emoji support across browsers and OSes is bad enough (e.g. Windows rendering flag emoji as letters) that most chat apps seem to want to just bring their own emoji everywhere.

A primary goal of this project is to optimize for performance, preferring native browser support wherever possible. Twemoji is a stretch, but I still think color font support would be pretty reasonable (doesn't require `<img>`s instead of text, is basically just a CSS change). However the browsers still don't agree on a color font format: https://github.com/nolanlawson/emoji-picker-element/issues/82#issuecomment-1045260517

**Comment by nolanlawson** [comment]
I looked into it, and it is possible to use Twemoji with `emoji-picker-element`. There is definitely a perf cost, and you'd probably want to host the image files yourself and do some other tweaks, but you can do it. Added a link to a [demo](https://bl.ocks.org/nolanlawson/fead700a0325aabd92670d56d6d422d8) to the README.

**Comment by r0hin** [comment]
Perfect- got it working. Though, consider adding a note to use `pointer-events: none` on the twemoji images so that click events still fire.
