### ISSUE TITLE
Custom emoji break the filter and color tone

### ISSUE THREAD

**Issue by RadekHavelka** [nolanlawson/emoji-picker-element#238]
Hello, 
  im trying to mix UTF emojis with custom emojis from images I do have on my existing site. I init the picker using the web component tag

`<emoji-picker></emoji-picker>`

and after that I add some custom emojis, let say

```
document.querySelector('emoji-picker').customEmoji =[{
      name: 'Very Happy',
      shortcodes: ['myown-veryhappy', ':D'],
      url: '/images/smiles/icon_biggrin.gif'
    }];

```    
    
using this, each time i try to use FILTER or change the color tone while I am on the first tab (custom icons) ONLY (it works on the classic emojis tabs), it breaks the picker completly, saying

`
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'removeChild')
    at detach (VM28402 picker.js:40)
    at Object.d (VM28402 picker.js:967)
    at destroy_block (VM28402 picker.js:157)
    at update_keyed_each (VM28402 picker.js:208)
    at Object.p (VM28402 picker.js:1060)
    at update_keyed_each (VM28402 picker.js:180)
    at Object.p (VM28402 picker.js:1601)
    at update (VM28402 picker.js:138)
    at flush (VM28402 picker.js:106)
`

please note those custom emojis do not have any UTF8 code, I am using the second value from shortcode array when inserting to my editor.

what am I doing wrong?

**Comment by RadekHavelka** [comment]
I had to add "category" to the data, with it the problem is gone. Obviously this sentence from doc

The category is optional. If you don't provide it, then the custom emoji will appear in a single category called "Custom".

is not true ;)

**Comment by nolanlawson** [comment]
I cannot seem to reproduce. Could you please let me know:

1. An unminified stacktrace (if possible)
2. Which browser are you using
3. Ideally a live site I can reproduce on :)

Here are my own steps to repro:

1. Clone this repo
2. `yarn && yarn dev`
3. Navigate to localhost:3000
4. Paste your above code into the DevTools console

Everything seems to work, even after I filter and change the skintone. Am I missing something?

![Screenshot from 2021-12-26 23-35-54](https://user-images.githubusercontent.com/283842/147447349-62a0f84b-ee39-4123-aa2a-559683bf4721.png)

**Comment by nolanlawson** [comment]
Closing, please reopen if you have a repro to share. Thank you!
