### ISSUE TITLE
'CustomElementRegistry': the name "emoji-picker" has already been used with this registry

### ISSUE THREAD

**Issue by AlbertQM** [nolanlawson/emoji-picker-element#245]
Hi! 👋 
      
Firstly, thanks for your work on this project! I found this library better than the other 3 ones I tried 😄 

I have two different scripts importing `emoji-picker-element` to my project, and when the second one tries to import it, it throws (as expected):
`Failed to execute 'define' on 'CustomElementRegistry': the name "emoji-picker" has already been used with this registry`

I was wondering if there's a reason for not checking for the existence of the custom element before defining it again?

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/emoji-picker-element/picker.js b/node_modules/emoji-picker-element/picker.js
index c650990..af07b2c 100644
--- a/node_modules/emoji-picker-element/picker.js
+++ b/node_modules/emoji-picker-element/picker.js
@@ -2593,6 +2593,6 @@ for (const prop of PROPS) {
 
 Object.defineProperties(PickerElement.prototype, definitions);
 
-customElements.define('emoji-picker', PickerElement);
+customElements.get('emoji-picker') || customElements.define('emoji-picker', PickerElement);
 
 export default PickerElement;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by nolanlawson** [comment]
It's interesting that this hasn't come up before. I guess yeah, bailing out if `emoji-picker` already exists is probably the best bet. No sense in throwing an error.

Ideally your bundler should avoid running the same module twice, but I get it, it's not always possible. :slightly_smiling_face:
