### ISSUE TITLE
Exit icon on picker?

### ISSUE THREAD

**Issue by dankirshner** [nolanlawson/emoji-picker-element#265]
Thanks, very nice!  I can toggle the picker with a button click per your example, but I'd also like an "X" icon at the top right of the picker.

I've tried to add an absolutely-positioned image (using jQuery append(); inspect says it's there, but I can't get it to show.  Any thoughts?

Thanks again.

**Comment by dankirshner** [comment]
A moment's thought said I could wrap the picker in a div and attach my "X" icon to that...

**Comment by nolanlawson** [comment]
Yep, this is a great solution! The goal is that you can build your own modal around emoji-picker-element, however you'd like. :slightly_smiling_face:
