### ISSUE TITLE
Add NotoColorEmoji font to emoji-picker?

### ISSUE THREAD

**Issue by dankirshner** [nolanlawson/emoji-picker-element#266]
This font allows country flag emojis to work in Windows 10/11: https://github.com/googlefonts/noto-emoji.  But I can't figure out how to apply it to the shadowRoot element where emoji-picker lives (while still relying on code from your cdn).  Any thoughts?  Thanks much!

**Comment by nolanlawson** [comment]
`emoji-picker-element` isn't really designed to allow for custom fonts, but you can kind of get it to work if you inject what you want into the shadow root. Here's an example using Twemoji: https://github.com/nolanlawson/emoji-picker-element#examples

**Comment by nolanlawson** [comment]
And yeah I agree it's too bad Windows doesn't have flag emoji; I really wish they'd fix that.
