### ISSUE TITLE
Windows 10/11 missing emoji flag support

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/emoji-picker-element#269]
Related: #268

Windows 10/11 currently [render flags as letters, not flags](https://answers.microsoft.com/en-us/windows/forum/all/where-are-the-flag-emoji-in-windows-10/93daa6e8-880a-48b1-9891-ab5bfbfbce98). Firefox has fixed this using their own flag emoji, but Chromium have [opted not to fix it](https://bugs.chromium.org/p/chromium/issues/detail?id=1209677).

My hope with `emoji-picker-element` is that eventually browsers and OSes would get their acts together and start supporting emoji more broadly. And aside from the glacial rollout of yearly emoji updates, this has largely been the case. (Windows 7 and IE 11, environments with no emoji support whatsoever, are slowly fading away.) But flag emoji on Windows are a big missing piece currently.

**Comment by nolanlawson** [comment]
I've already filed bugs on Chromium and added instructions to the README for a workaround. There's not much more I can do here, so closing this issue.

**Comment by nolanlawson** [comment]
Amazing, there is even a Chrome extension to fix this :smiling_face_with_tear: https://bugs.chromium.org/p/chromium/issues/detail?id=1209677#c6

**Comment by safaEF** [comment]
add this 

```
<script type="module" src="https://cdn.jsdelivr.net/npm/emoji-picker-element@^1/index.js"></script>
<script type="module">
  import { polyfillCountryFlagEmojis } from 'https://cdn.skypack.dev/country-flag-emoji-polyfill@v0.1.1'

  polyfillCountryFlagEmojis('Twemoji Mozilla')
</script> 
```

in the index.html

**Comment by tuannvbg** [comment]
https://github.com/tuannvbg/unicode-flags-for-windows` --> Solutions for everyone 🥰 🇻🇳 🇺🇸
