### ISSUE TITLE
Sapper - ReferenceError: requestAnimationFrame is not defined

### ISSUE THREAD

**Issue by gavinr** [nolanlawson/emoji-picker-element#27]
In a svelte component within a Sapper project, I am trying to add the picker:

```
<script>
  import { onMount } from "svelte";

  // https://github.com/nolanlawson/emoji-picker-element#within-a-svelte-project
  import Picker from "emoji-picker-element/svelte";

  let sidebar;

  onMount(() => {

    // Picker:
    const picker = new Picker({
      locale: "en",
    });
    sidebar.appendChild(picker);
  });
</script>

<div bind:this={sidebar}></div>
```

error:
```
const rAF = requestAnimationFrame;
            ^
ReferenceError: requestAnimationFrame is not defined
```

Any ideas or advice on how to get this running in sapper? Thanks!

**Comment by gavinr** [comment]
Found the answer: follow this: https://sapper.svelte.dev/docs#Making_a_component_SSR_compatible

So something like this:

```
onMount(async () => {
    // Picker:
    const Picker = await import("emoji-picker-element/svelte");

    const picker = new Picker.default({
      locale: "en",
    });
    sidebar.appendChild(picker);
  });
```

I hope this helps someone else out in the future!

**Comment by nolanlawson** [comment]
Yes, this is a good idea. `emoji-picker-element` relies on having access to the DOM, so it won't work in a Sapper environment where it tries to simultaneously server-render and client-render.

Another option I frequently do in Sapper projects is to ignore certain dependencies for the server side. You can do this in your Webpack/Rollup config, e.g. swap out the dependency for `lodash/noop` or something else when in a server side environment.

Dynamic importing works too. In fact it may be better for performance because it's lazy-loaded.

**Comment by wobsoriano** [comment]
> Found the answer - use a "dynamic import" - follow this: https://sapper.svelte.dev/docs#Making_a_component_SSR_compatible
> 
> So something like this:
> 
> ```
> onMount(async () => {
>     // Picker:
>     const Picker = await import("emoji-picker-element/svelte");
> 
>     const picker = new Picker.default({
>       locale: "en",
>     });
>     sidebar.appendChild(picker);
>   });
> ```
> 
> I hope this helps someone else out in the future!

Thanks. Works with Nuxt.

```js
export default defineComponent({
  name: 'AppEmojiPicker',
  emits: ['handleClick'],
  setup(_props, { emit }) {
    const pickerContainer = ref<HTMLDivElement>();
    const picker = ref();

    const handleClick = (event) => {
      emit('handleClick', event.detail.unicode);
    };

    onMounted(async () => {
      const Picker = await import('emoji-picker-element/picker');

      // eslint-disable-next-line new-cap
      picker.value = new Picker.default();

      if (pickerContainer.value) {
        pickerContainer.value.appendChild(picker.value);
        picker.value.addEventListener('emoji-click', handleClick, true);
      }
    });

    onUnmounted(() => {
      if (picker.value) {
        picker.value.removeEventListener('emoji-click', handleClick, true);
      }
    });

    return {
      pickerContainer,
      picker,
    };
  },
});
```
