### ISSUE TITLE
Can't hide the search-bar?

### ISSUE THREAD

**Issue by MariyanK1** [nolanlawson/emoji-picker-element#273]
Hey, guys.

You did a great job with this tool. Easy to use and efficient.

But I can't hide the search bar? How can I do it? 

I tried:

```
 emoji-picker {
          --num-columns: 10;
          --emoji-size: 1.1em;
          max-height: 186px;
          width: 100%;

          .picker {
            .search-row {
              display: none;
            }
          }
      }
```

I'm using scss but it doesn't work.

Any suggestions?

**Comment by nolanlawson** [comment]
Currently there is no way to hide the search bar. To remove it, refer to the [custom styling guide](https://github.com/nolanlawson/emoji-picker-element#custom-styling), e.g.:

```js
const style = document.createElement('style');
style.textContent = '.search-row, .pad-top { display: none; }';
document.querySelector('emoji-picker').shadowRoot.appendChild(style);
```

**Comment by MariyanK1** [comment]
Oh, I see. Thanks man and keep up the good work.
