### ISSUE TITLE
Bug in the demo

### ISSUE THREAD

**Issue by guidouil** [nolanlawson/emoji-picker-element#276]
On the [Demo website](https://nolanlawson.github.io/emoji-picker-element/)

If you check "Custom emoji" then click on the flag tab then uncheck "Custom emoji"
The emoji picker freeze with an error in the console :

`picker.js:843 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')`

**Comment by nolanlawson** [comment]
Thank you, confirmed. Looks like a bug when dynamically adding or remove custom emoji.
