### ISSUE TITLE
Change border-radius of the picker

### ISSUE THREAD

**Issue by osymo** [nolanlawson/emoji-picker-element#283]
Hello.

Is it possible to change the border radius of the picker ?

I tried multiple ways that seemed logic but none of them worked.

Thank you.

**Comment by nolanlawson** [comment]
It is not currently supported in the official API. However, you can always use the custom styling API described here: https://github.com/nolanlawson/emoji-picker-element#custom-styling

Hope that helps!

**Comment by JVariance** [comment]
@nolanlawson It'd be great to have border-radius also as an CSS-variable.
