### ISSUE TITLE
Possibility to change input field font type

### ISSUE THREAD

**Issue by larrycaw** [nolanlawson/emoji-picker-element#292]
Hi! I'm missing the possibility to change the search input fields font. As of now, it's only possible to change category-font-color, category-font-size, input-font-color and input-font-size.

**Comment by nolanlawson** [comment]
Hi, as of right now you can either set the font-family outside of the element and have it inherit in, or you can add whatever styles you want using this technique: https://github.com/nolanlawson/emoji-picker-element#custom-styling

Hope that helps! Thanks
