### ISSUE TITLE
allow overriding emoji support detection

### ISSUE THREAD

**Issue by easrng** [nolanlawson/emoji-picker-element#305]
In my fork of Pinafore (which you used emoji-picker-element in) I've implemented a polyfill for unsupported Unicode emojis, which is working great, but I can't insert them with the picker. Ideally I'd be able to pass in a function overriding the default detector and a function that's called with a reference to newly-rendered emojis. Would you be open to a PR implementing this?

**Comment by easrng** [comment]
Actually I decided I'm going to use color fonts instead of images, so I don't *need* this, but it still seems wasteful to do detection multiple times.

**Comment by nolanlawson** [comment]
Yeah I had started doing some work on #82 (custom fonts) which would imply that you can disable detection entirely. However I have not yet finished that work.

It seems to me that this issue is a duplicate of #82?

**Comment by easrng** [comment]
Yeah, I guess it is now.
