### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by toschlog** [nolanlawson/emoji-picker-element#326]
I found the following in my crash reporting service:

![Capture](https://user-images.githubusercontent.com/25090868/230134373-a22452db-5568-48e1-bb94-2d349f310e6b.PNG)

However, I'm using an old version (1.3.4) so maybe this is an issue that's already been fixed.  I'll update to 1.16.0.

**Comment by nolanlawson** [comment]
Yes, this issue has been fixed in a recent version. I forget exactly when it was fixed, but you can see that the latest code handles this:

https://github.com/nolanlawson/emoji-picker-element/blob/69b2f81e551a74da52dc0030e2db8880cd4ff766/src/picker/utils/resetScrollTopIfPossible.js#L1-L10
