### ISSUE TITLE
Rounded borders for the pop-up

### ISSUE THREAD

**Issue by EndlessRecurrence** [nolanlawson/emoji-picker-element#327]
Hello,
Is there any method that could be used to round the borders of the pop-up? I've seen that it is possible to use border-radius for the input element within the pop-up, but not for the border of the whole pop-up, which is quite weird.

**Comment by nolanlawson** [comment]
You can style things however you want using this technique: https://github.com/nolanlawson/emoji-picker-element#custom-styling

Hope that helps!

**Comment by EndlessRecurrence** [comment]
Thanks for the guidance, I'll check that out now.

**Comment by EndlessRecurrence** [comment]
It definitely works, thank you. 
For those who are confused: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM
