### ISSUE TITLE
Underscores in when hovering over emoji in the picker

### ISSUE THREAD

**Issue by rch77** [nolanlawson/emoji-picker-element#366]
Is there way to get rid of the underscores in the title and aria-label? It looks odd.
I think the picker uses shortcodes from the db while it should use annotation.

**Comment by nolanlawson** [comment]
Thanks for opening the issue! Could you be more specific about what you're looking for? Do you want to:

1. Disable the `title` (hover) entirely?
2. Replace the underscores with a space character (or something)?

Right now this data comes directly from `emoji-picker-element-data`, which gets the `shortcodes` directly from `emojibase-data`, but maybe we can offer an option to do something else.

**Comment by rch77** [comment]
Thank you for the response. I would like the title (hover) to come from the `annotation` field in the db. I.e. without underscores in human readable form so that somebody hovering over it would be able to read it as descriptive English text not some code. As in the screenshot below, "cloud with lightning and rain" instead of "stormy, thunder_cloud_and_rain" it uses now.
![image](https://github.com/nolanlawson/emoji-picker-element/assets/83680014/ca543c70-41be-4757-a5c6-31688aa597fd)
Some of the `shortcodes` values in the db are not even human readable. E.g. shortcodes:0:"ja_here" with annotation:"Japanese “here” button".

**Comment by nolanlawson** [comment]
Yeah this is a good point – the shortcode hover was mostly designed for usecases like a social media app where you might actually use the shortcodes and even memorize a few.

I'm totally fine with just making the default the annotation. If someone complains and wants the shortcode back, we can use that instead.

BTW this isn't really an integral part of the experience – you can only see it if you have a mouse or you're a screenreader user, e.g. sighted mobile users would never be able to see this.
