### ISSUE TITLE
Support emojibase-data v6

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/emoji-picker-element#47]
Looks like `emojibase-data` v6 has been released, with several breaking changes that affect `emoji-picker-element`: https://github.com/milesj/emojibase/blob/master/packages/data/CHANGELOG.md#600---2020-09-11

Luckily we are not broken by default, because I had the foresight to make the default URL `https://cdn.jsdelivr.net/npm/emojibase-data@5/en/data.json`.

**Comment by nolanlawson** [comment]
It seems the trickiest part is that `shortcodes` have been removed entirely and moved to separate files (https://github.com/milesj/emojibase/pull/64). These files vary based on source (emojibase, GitHub, JoyPixels, etc.).

Unfortunately `emoji-picker-element` assumes one JSON file as the source, and having multiple would make things awkward given how caching/invalidation works.

Options:

1. Remove the shortcodes entirely (would probably degrade the search experience)

2. Allow for loading the shortcodes JSON separately (extra logic to handle caching/invalidation, one extra request, but as a benefit, people could choose their own shortcodes JSON)

3. Make `trimEmojiData.js` into a required step – i.e., emoji-picker-element users _must_ build their own single JSON file from two separate emojibase-data JSON files (the main data and the shortcodes data).

I'm not sure what to do, but I'm wavering between # 2 and # 3. Perhaps if we host our own copy of the data, then there will be minimal disruption for people who want to just grab the `emoji-picker-element` JS file and not think about where the data comes from. But then we would have to switch from jsdelivr to our own thing (or apply to join jsdelivr ourselves). Also this would imply that we re-release every time emojibase-data releases.

**Comment by MayeulC** [comment]
Except for 2., does that implies you are foregoing shortcodes localization?

**Comment by nolanlawson** [comment]
@MayeulC My assumption is that people would choose their own shortcode JSON and emoji JSON. So localization would be handled by the consumer of `emoji-picker-element` (as it is today).

**Comment by nolanlawson** [comment]
Interestingly, with emojibase-data v6, it looks like we can't depend on the `shortcodes` being there. They're missing for some shortcode packs (e.g. `github.json` doesn't have "smiling face with tear").
