### ISSUE TITLE
How to use completely offline hosting the data packs?

### ISSUE THREAD

**Issue by LiamDawe** [nolanlawson/emoji-picker-element#480]
Hi, for those of us who don't wish to use a CDN which comes with all sorts of GDPR / privacy issues on loading external data, and for people who don't use stuff like NPM. How exactly can we set this up?

Could you please add instructions on what we need to download exactly from where, and what script tags to include in our code?

I assume it's just similar to the:

> Or as a <script> tag:

Instructions, but changing the index.js to our directory, it just needs the added steps of providing the data packs ourselves. Would love to see this simple thing added in the docs there.

**Comment by nolanlawson** [comment]
I couldn't really find a good place to put this in the README, but basically:

The emoji data can be downloaded [from jsdelivr](https://cdn.jsdelivr.net/npm/emoji-picker-element-data@^1/en/emojibase/data.json).

The picker itself by downloading all `*.js` files [from jsdelivr](https://cdn.jsdelivr.net/npm/emoji-picker-element@%5E1/). `index.js` is the root file. You'll probably want the `LICENSE` file too.

Hope that answers your question!
