### ISSUE TITLE
How to remove the Flags category?

### ISSUE THREAD

**Issue by sonnyk22** [nolanlawson/emoji-picker-element#485]
Great library!  Thank you.

As seen in the figure below, how can we remove the Flags category? Or how to provide it with proper countries emojis?

![flags](https://github.com/user-attachments/assets/d3b0c339-be5a-411a-abb5-dba958a25c93)

**Comment by nolanlawson** [comment]
Please see the section in the README: [Polyfilling flag emoji on Windows](https://github.com/nolanlawson/emoji-picker-element?tab=readme-ov-file#polyfilling-flag-emoji-on-windows). Hope that helps!
