### ISSUE TITLE
How to get only main subset emojis?

### ISSUE THREAD

**Issue by sonnyk22** [nolanlawson/emoji-picker-element#486]
Is there a way to only get the main bottom part subset Emojis, as seen below?

![subset](https://github.com/user-attachments/assets/279f1d7a-c61e-4637-bb6d-935217b098b1)

**Comment by nolanlawson** [comment]
I don't understand the question. Are you asking if it's possible to show the favorites bar without showing any other part of the emoji picker? Currently this is not possible, but you could fork the project with something like [`patch-package`](https://www.npmjs.com/package/patch-package) to achieve this.
