### ISSUE TITLE
See bundlesize reports

### ISSUE THREAD

**Issue by szepeviktor** [nolanlawson/emoji-picker-element#52]
Please authorize bundlesize to see its reports.

![kép](https://user-images.githubusercontent.com/952007/94350112-3cf26d80-004b-11eb-968a-97d5689c65c1.png)

https://github.com/siddharthkp/bundlesize#build-status-for-github

**Comment by nolanlawson** [comment]
I considered doing this, but I was a bit on-the-fence about authorizing a new GitHub app just to see the bundlesize in PRs. But yeah, it is cool functionality!
