### ISSUE TITLE
Set picker as Button with Overlay

### ISSUE THREAD

**Issue by Ravisdo** [nolanlawson/emoji-picker-element#57]
Hello there, first of all, amazing work here.

How I can set the Picker as a Button with floating overlay such as datepicker?

Here my code
```html
<a id="emojiPicker" class="btn btn-primary" type="button">Emoji</a>
```
```js
        <script type="module">
            let picker = new emoji_picker.Picker();
            let style = document.createElement('style');
            style.textContent = `
            .picker {
    z-index: 1;
    position: relative;
    width: auto;
}
            `
            picker.shadowRoot.appendChild(style);
            let emojiPicker = $('#emojiPicker');
            emojiPicker.click(function() {
                $('#emojiPicker').after(picker);
            });

            const pre = $('#pre')
            const onEvent = e => {
                console.log(e)
                pre.html(`Event: ${JSON.stringify(e.type)}\n\nData:\n\n${JSON.stringify(e.detail, null, 2)}`);
            }
            picker.addEventListener('emoji-click', onEvent);
        </script>
```

I'm not that good in JS and JQuery that i can exactly describe the wanted behavior. 
On Datepicker Plugin, if you click into an input field for example it will show a nice "overlay" popup
https://jqueryui.com/datepicker/

Is it posible to do that for this project?

**Comment by nolanlawson** [comment]
Probably the best way would be to use some kind of tooltip library, such as [TippyJS](https://atomiks.github.io/tippyjs/) or [PopperJS](https://popper.js.org). As long as it allows arbitrary HTML, you can just include the HTML for `<emoji-picker-element>`.

I was curious about how you might do this, so I actually whipped up [a quick example](https://bl.ocks.org/nolanlawson/781e7084e4c17acb921357489d51a5b0). The code is fairly straightforward (important parts below):

```html
<style>
  .tooltip:not(.shown) {
    display: none;
  }
</style>
<button onclick="toggle()">Click me</button>
<div class="tooltip" role="tooltip"><emoji-picker></emoji-picker></div>
<script>
  const button = document.querySelector('button')
  const tooltip = document.querySelector('.tooltip')
  Popper.createPopper(button, tooltip)

  function toggle() {
    tooltip.classList.toggle('shown')
  }
</script>
```

Hope that helps!
